apiVersion: v1
kind: Namespace
metadata:
  name: chatwoot
  labels:
    name: chatwoot
    app.kubernetes.io/name: chatwoot
    app.kubernetes.io/part-of: chatwoot-platform
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: chatwoot-quota
  namespace: chatwoot
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: chatwoot-limits
  namespace: chatwoot
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container